[package]
name = "aur"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
metaflac = "0.2"
anyhow = "1.0"
id3 = "1.14"
mp3-metadata = "0.3"
terminal_size = "0.4"
# unicode-normalization = "0.1"
unidecode = "0.3"
regex = "1"

[dev-dependencies]
tempfile = "3.13"
assert_cli = "0.6"
assert_fs = "1.1"
