[package]
name = "aur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
id3 = "1.14"
indicatif = "0.17"
lazy_static = "1.5"
metaflac = "0.2"
mp3-metadata = "0.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
terminal_size = "0.4"
toml = "0.8"
unidecode = "0.3"
once_cell = "1.20"


[dev-dependencies]
assert_cli = "0.6"
assert_fs = "1.1"
assert_unordered = "0.3"
tempfile = "3.13"
