[package]
name = "aur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
id3 = "1.14"
lazy_static = "1.5"
metaflac = "0.2"
mp3-metadata = "0.3"
regex = "1"
terminal_size = "0.4"
unidecode = "0.3"
indicatif = "0.17"

[dev-dependencies]
assert_cli = "0.6"
assert_fs = "1.1"
tempfile = "3.13"
assert_unordered = "0.3"
