all_caps = [
  "cd",
  "diy",
  "dvd",
  "ep",
  "ii",
  "iii",
  "iv",
  "ix",
  "lp",
  "ok",
  "ps",
  "uk",
  "usa",
  "vi",
  "vii",
  "viii",
  "xi",
  "xii",
  "xiii",
  "xiv",
  "xix",
  "xv",
  "xvi",
  "xvii",
  "xviii",
  "xx",
  "xxi",
  "xxv",
  "xxx",
]

no_caps = [
  "a",
  "am",
  "an",
  "and",
  "are",
  "as",
  "at",
  "au",
  "by",
  "ce",
  "dans",
  "de",
  "des",
  "du",
  "es",
  "est",
  "et",
  "feat",
  "featuring",
  "for",
  "from",
  "in",
  "into",
  "is",
  "it",
  "its",
  "la",
  "le",
  "ne",
  "nor",
  "o'clock",
  "of",
  "off",
  "on",
  "onto",
  "or",
  "out",
  "pas",
  "per",
  "se",
  "so",
  "te",
  "than",
  "that",
  "the",
  "till",
  "to",
  "too",
  "un",
  "une",
  "via",
  "vs",
  "when",
  "with",
]

ignore_case = [
  "x",
]

[expand] 
"12inch" = "12\""
<<<<<<< HEAD
"7inch" = "7\""
=======
"7inch'" = "7\""
>>>>>>> fe062e7 (rough out some titlecase stuff)
"--" =  " - " 
"'&'" = "and"
"aint" = "ain't"
"cant" = "can't"
"couldnt" = "couldn't"
"didnt" = "didn't"
"dj" = "DJ"
"doesnt" = "doesn't"
"dont" = "don't"
"etc" = "etc."
"ft" = "featuring"
"hes" = "he's"
"havent" = "haven't"
"ive" = "I've"
"im" = "I'm"
"isnt" = "isn't"
"its" = "it's"
"lets" = "let's"
"n" = "'n'"
"shes" = "she's"
"thats" = "that's"
"theres" = "there's"
"wasnt" = "wasn't"
"weve" = "we've"
"whats" = "what's"
"whos" = "who's"
"wont" = "won't"
"wouldnt" = "wouldn't"
"youll" = "you'll"
"youre" = "you're"
"youve" = "you've"


