name: Test 
permissions:
  contents: read
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install external dependencies
      run: sudo apt-get update && sudo apt-get install -y lame flac ffmpeg mp3val
    - name: Run tests
      run: cargo test -- --include-ignored
