name: Test 
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install external dependencies
      run: sudo apt-get update && sudo apt-get install -y lame flac ffmpeg mp3val
    - name: Run tests
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48
      with:
        toolchain: stable,nightly
    - run: cargo test --verbose -- --include-ignored
