name: Test 
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
    steps:
    - name: Install LAME
      run: sudo apt-get update && sudo apt-get install -y lame
    - uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
    - name: Move ffmpeg to /usr/bin
      run: |
        mkdir -p /opt/ooce/bin
        cp $(which ffmpeg) /opt/ooce/bin
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose -- --include-ignored
